# Regex full guide

In [14]:
import pandas as pd

### Basic matching

In [15]:
df = pd.DataFrame({
    'notes': [
        'apple pie is tasty',
        'banana bread is sweet',
        'apple grapes juice is healthy',
        'grapes are fresh',
        'pineapple tart',
        'abcdefg'
    ]
})

#going to find the data rows containing the word apple

display(df[df["notes"].str.contains("apple",case=False,na=False)])

                           notes
0             apple pie is tasty
2  apple grapes juice is healthy
4                 pineapple tart

### Extracting substrings

In [16]:
df["fruits"]=df["notes"].str.extract(r'(apple|banana|grapes|pineapple)')
display(df.head())

                           notes     fruits
0             apple pie is tasty      apple
1          banana bread is sweet     banana
2  apple grapes juice is healthy      apple
3               grapes are fresh     grapes
4                 pineapple tart  pineapple

* The above code only finds the first valid string and retun it

In [17]:
df["fruits"]=df['notes'].str.findall(r'(apple|banana|grapes|pineapple)')
display(df)

                           notes           fruits
0             apple pie is tasty          [apple]
1          banana bread is sweet         [banana]
2  apple grapes juice is healthy  [apple, grapes]
3               grapes are fresh         [grapes]
4                 pineapple tart      [pineapple]
5                        abcdefg               []